version: '3.8'

services:
  dagster:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../data:/app/data
      - ../.env:/app/.env
    environment:
      - DAGSTER_HOME=/app
    command: dagster dev -h 0.0.0.0

  dashboard:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../data:/app/data
      - ../.env:/app/.env
    command: streamlit run dashboard/app.py --server.address=0.0.0.0
    depends_on:
      - dagster

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dagster
      POSTGRES_PASSWORD: dagster
      POSTGRES_DB: dagster
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
